#!/bin/bash
# Quick Start Guide for Mesh Audio Network ISO
# ==============================================

echo "╔══════════════════════════════════════════════════════════╗"
echo "║        MESH AUDIO NETWORK - QUICK START GUIDE             ║"
echo "╚══════════════════════════════════════════════════════════╝"
echo ""

# Check what we have
PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$PROJECT_DIR"

echo "📋 Project Status:"
echo "   - Configuration: $(ls nixos-config/*.nix 2>/dev/null | wc -l) NixOS files"
echo "   - Software: $(ls software/build/ 2>/dev/null | wc -l) binaries"
echo "   - Songs: $(ls songs/all_songs/ 2>/dev/null | wc -l) in all_songs/"
echo ""

echo "📦 To Build the ISO (requires Linux with Nix):"
echo ""
echo "   Option 1: Using build script"
echo "   $ chmod +x build_iso.sh"
echo "   $ ./build_iso.sh"
echo ""
echo "   Option 2: Using Docker"
echo "   $ docker build -t mesh-iso ."
echo "   $ docker run -v \$(pwd)/output:/output mesh-iso"
echo ""
echo "   Option 3: Manual NixOS build"
echo "   $ nix-build '<nixos>' -A config.system.build.isoImage \\\\"
echo "       --arg configuration ./nixos-config/configuration.nix \\\\"
echo "       -o result"
echo ""

echo "💿 To Flash to USB (after ISO is built):"
echo ""
echo "   $ sudo dd if=output/mesh-audio.iso of=/dev/sdX bs=4M status=progress"
echo "   $ sync"
echo ""
echo "   ⚠️  Replace /dev/sdX with your USB device!"
echo ""

echo "🚀 To Run the Software (on the booted system):"
echo ""
echo "   # Start mesh agent (discovers peers, elects master)"
echo "   $ ./software/build/mesh-agent &"
echo ""
echo "   # Start API server"
echo "   $ ./software/build/mesh-api &"
echo ""
echo "   # Start monitor TUI"
echo "   $ ./software/build/mesh-monitor"
echo ""

echo "🔧 Mesh Networking Setup:"
echo ""
echo "   # Setup batman-adv mesh"
echo "   $ modprobe batman-adv"
echo "   $ ip link set up dev wlan0"
echo "   $ batctl meshif wlan0 join MESH-AUDIO"
echo ""
echo "   # Or use NetworkManager"
echo "   $ nmtui"
echo ""

echo "🌐 API Endpoints:"
echo ""
echo "   curl http://localhost:8080/health      # Health check"
echo "   curl http://localhost:8080/status       # Node status"
echo "   curl http://localhost:8080/metrics     # Network metrics"
echo "   curl http://localhost:8080/peers       # Connected peers"
echo "   curl http://localhost:8080/songs       # Local songs"
echo "   curl -X POST -d '{\"song\":\"song.wav\"}' http://localhost:8080/set-song"
echo ""

echo "📊 Indicators Displayed:"
echo ""
echo "   ✓ TX Rate (Mbps) - Transmission rate"
echo "   ✓ Signal (dBm) - Signal strength with peers"
echo "   ✓ Modulation - QPSK, 16-QAM, 64-QAM, 256-QAM"
echo "   ✓ Active Peers - Nodes in range"
echo "   ✓ Local Songs - Songs on this node (25)"
echo "   ✓ Streaming Song - Current song from master"
echo ""

echo "👤 Default Credentials:"
echo "   User: mesh / Password: mesh123"
echo "   Root: root / Password: root123"
echo ""

echo "╔══════════════════════════════════════════════════════════╗"
echo "║           Build completed! Ready to compile ISO.         ║"
echo "╚══════════════════════════════════════════════════════════╝"